### ISSUE TITLE
Unable to use existing secrets

### ISSUE THREAD

**Issue by MuhanedYahya** [paradedb/charts#2]
**Bug Description**
When appUserCredentials and superUserCredentials are provided via values.yaml, new secrets are created during deployment. If these secrets already exist, the deployment fails with an error. This issue prevents the deployment of Paradedb in environments where sealed-secrets are used, as it cannot handle pre-existing secrets.

**Proposed Fix**
add option like (`existingSecret: SECRET_ NAME)` under both of the sections appUserCredentials and superUserCredentials without the need to enter other values

After the correction I expect:
```
auth:
  appUserCredentials:
    existingSecret: app-user-secret
    # name: 
    # # Password for the app user (base64 encoded).
    # password: 
    # # Username for the app user (base64 encoded)
    # username: 

  superUserCredentials:
    existingSecret: super-user-secret
    # name: 
    # # Password for the superuser (base64 encoded).
    # password: 
    # # Username for the superuser (base64 encoded)
    # username: 

  # backupCredentials:
  #   existingSecret: backup-secret
  #   name: 
  #   # AWS ACCESS_KEY_ID (base64 encoded)
  #   accessKeyId: 
  #   # AWS ACCESS_SECRET_KEY (base64 encoded)
  #   accessSecretKey: 
```
